services:
  mongo:
    image: mongo:8
    container_name: mongodb
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - node-app-network
    restart: on-failure
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
networks:
  node-app-network:
    driver: bridge