services:
  mongo:
    image: mongo:8
    container_name: mongodb-nodems
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - node-app-network
    restart: on-failure
    volumes:
      - mongo-data:/data/db
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - node-app-network
    restart: on-failure
    volumes:
      - redis-data:/data

  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - node-app-network
    restart: on-failure 

volumes:
  mongo-data:
  redis-data:
  
networks:
  node-app-network:
    driver: bridge